name: Dry-run

on:
  workflow_dispatch:  # This allows manual triggering

jobs:
  get-release-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Find release tag
        id: get_release_tag
        run: |
          RESPONSE=$(curl -s "https://registry.hub.docker.com/v2/repositories/gitpod/openvscode-server/tags?page_size=100")
          RELEASE_TAG=$(echo $RESPONSE | jq -r '
            .results as $results |
            $results | map(.name == "latest") | index(true) as $latest_index |
            if $latest_index != null then
              $results[$latest_index].digest as $latest_digest |
              $results[$latest_index+1:] | map(select(.digest == $latest_digest)) | first | .name
            else
              null
            end
          ')
          if [ -z "$RELEASE_TAG" ]; then
            RELEASE_TAG="latest"
            echo "No specific release tag found after 'latest', using 'latest'"
          fi
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "Release tag: $RELEASE_TAG"

      - name: Use the release tag
        run: |
          echo "The release tag is ${{ steps.get_release_tag.outputs.RELEASE_TAG }}"
        # You can use this version in subsequent steps or jobs
