name: Dry-run

on:
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  dry_run:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest tag of openvscode-server from Docker Hub
        id: get_version
        run: |
          RESPONSE=$(curl -s "https://hub.docker.com/v2/repositories/gitpod/openvscode-server/tags/?page_size=1&ordering=last_updated")
          LATEST_TAG=$(echo $RESPONSE | jq -r '.results[0].name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_OUTPUT
          echo "Latest OpenVSCode Server tag: $LATEST_TAG"

      - name: Print the openvscode-server version
        run: |
          echo "The latest version is ${{ steps.get_version.outputs.LATEST_TAG }}"
